### ISSUE TITLE
Dependency failing

### ISSUE THREAD

**Issue by ltatakis** [openphacts/Void-Editor2#4]
The validator dependency fails to be downloaded. Is the mygrid service down or deprecated?

`uk.ac.manchester.cs.datadesc.validator:rdf-tools:jar:1.1.0: Could not transfer artifact uk.ac.manchester.cs.datadesc.validator:rdf-tools:pom:1.1.0 from/to mygrid-ops (http://repository.mygrid.org.uk/artifactory/ops): Failed to transfer file: http://repository.mygrid.org.uk/artifactory/ops/uk/ac/manchester/cs/datadesc/validator/rdf-tools/1.1.0/rdf-tools-1.1.0.pom. Return code is: 503`

Occurs when I run `mvn clean package -DskipTests`.

@stain  any ideas? 

Should we remove validator dependency? the RDF validator was only a cherry we added in the code for my undergraduate thesis.

**Comment by AlasdairGray** [comment]
Validating the generated descriptions is important, but if all the logic is already hardcoded in the JS then it is probably safe and potentially wise to remove the dependency on the validator

**Comment by ltatakis** [comment]
Removed dependency of validator as logic is hard coded.

**Comment by stain** [comment]
The `repository.mygrid.org.uk` artifactory server is unexpectedly down, looking at it now.
